# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('describe', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='UnitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IEPC', models.CharField(max_length=200)),
                ('Time', models.TimeField()),
                ('Phase', models.IntegerField()),
                ('RSSI', models.IntegerField()),
                ('Doppler', models.IntegerField()),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Case')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.User'),
        ),
    ]
